language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="cconv:. cconv-ppx:."
  - DISTRO="ubuntu-16.04"
  matrix:
  - PACKAGE="cconv" OCAML_VERSION="4.03" EXTRA_DEPS="bencode" TESTS=false
  - PACKAGE="cconv" OCAML_VERSION="4.04" EXTRA_DEPS="bencode" TESTS=false
  - PACKAGE="cconv" OCAML_VERSION="4.06" EXTRA_DEPS="bencode" TESTS=false
  - PACKAGE="cconv" OCAML_VERSION="4.07" EXTRA_DEPS="bencode" TESTS=false
  - PACKAGE="cconv-ppx" OCAML_VERSION="4.02.3"
  - PACKAGE="cconv-ppx" OCAML_VERSION="4.03"
  - PACKAGE="cconv-ppx" OCAML_VERSION="4.04"
  - PACKAGE="cconv-ppx" OCAML_VERSION="4.06"
  - PACKAGE="cconv-ppx" OCAML_VERSION="4.07"
